# Generated by Django 2.0.6 on 2018-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='customer_code',
            field=models.CharField(default='FAKE_CODE', max_length=300),
        ),
    ]
