# Generated by Django 2.0.6 on 2018-11-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0002_auto_20181114_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='customer_code',
            field=models.CharField(blank=True, default='FAKE_CODE', max_length=300, null=True),
        ),
    ]
