# Generated by Django 2.0.6 on 2018-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0004_auto_20181116_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionactionstatus',
            name='question_action_select_status',
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='drop_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='run_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='status_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='status_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer',
            field=models.BooleanField(),
        ),
    ]
