# Generated by Django 2.0.6 on 2018-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0005_auto_20181116_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionactionstatus',
            old_name='status_id',
            new_name='drop_status_name',
        ),
        migrations.RenameField(
            model_name='questionactionstatus',
            old_name='status_name',
            new_name='run_status_name',
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='drop_status_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='run_status_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
