# Generated by Django 2.0.6 on 2018-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0006_auto_20181116_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionactionstatus',
            name='drop_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionactionstatus',
            name='drop_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionactionstatus',
            name='drop_status_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='questionactionstatus',
            name='run_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionactionstatus',
            name='run_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionactionstatus',
            name='run_status_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
