# Generated by Django 2.0.6 on 2018-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0007_auto_20181116_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionactionlogtype',
            name='question_action_log_type',
        ),
        migrations.AddField(
            model_name='questionactionlogtype',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionactionlogtype',
            name='type_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
