# Generated by Django 2.0.6 on 2018-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0008_auto_20181116_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionactionlogtype',
            name='question_action_log_type',
            field=models.CharField(choices=[('log type', 'LOG TYPE'), ('error', 'ERROR'), ('warning', 'WARNING'), ('info', 'INFO'), ('action', 'ACTION'), ('gps coords', 'GPS COORDS')], default='select log type', max_length=40),
        ),
        migrations.AddField(
            model_name='questionactionstatus',
            name='question_action_select_status',
            field=models.CharField(choices=[('select status', 'SELECT STATUS'), ('50', '50'), ('100', '100'), ('150', '150'), ('200', '200'), ('300', '300'), ('500', '500')], default='select status', max_length=40),
        ),
    ]
