# Generated by Django 2.0.6 on 2018-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0009_auto_20181116_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionactionlogtype',
            name='question_action_log_type',
        ),
        migrations.RemoveField(
            model_name='questionactionstatus',
            name='question_action_select_status',
        ),
    ]
