# Generated by Django 2.0.6 on 2018-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0010_auto_20181116_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunsheetData',
            new_name='QuestionLog',
        ),
        migrations.AlterModelOptions(
            name='questionlog',
            options={'verbose_name_plural': 'question Log'},
        ),
        migrations.RenameField(
            model_name='questionresponse',
            old_name='driver_id',
            new_name='question_section',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question_data',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question_text',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
