# Generated by Django 2.0.6 on 2018-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0011_auto_20181116_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='question_answer',
            field=models.BooleanField (default=False,blank=True),
        ),
    ]
