# Generated by Django 2.0.6 on 2018-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0012_auto_20181116_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlog',
            name='log_type',
            field=models.DateTimeField(),
        ),
    ]
