# Generated by Django 2.0.6 on 2018-11-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0013_auto_20181116_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlog',
            old_name='log_type',
            new_name='log_entry_type',
        ),
    ]
