# Generated by Django 2.0.6 on 2018-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0014_auto_20181116_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='log_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
