# Generated by Django 2.0.6 on 2018-11-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0016_remove_questionlog_log_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionactionlog',
            name='question_action_log_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questionactionlog',
            name='question_action_log_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApi.QuestionActionLogType'),
        ),
    ]
