# Generated by Django 2.0.6 on 2018-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0017_auto_20181117_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_directory',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(default='no-img.jpg', upload_to=''),
        ),
    ]
