# Generated by Django 2.0.6 on 2018-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0018_auto_20181117_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_directory',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(default='static/project_pictures/no-img.jpg', upload_to='static/project_pictures'),
        ),
    ]
