# Generated by Django 2.0.6 on 2018-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0019_auto_20181117_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_directory',
            field=models.FileField(default='branch_pictures/no-img.jpg', upload_to='branch_pictures'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(default='organisation_pictures/no-img.jpg', upload_to='organisation_pictures'),
        ),
    ]
