# Generated by Django 2.0.6 on 2018-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0020_auto_20181117_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_directory',
            field=models.CharField(max_length=300),
        ),
    ]
