# Generated by Django 2.0.6 on 2018-11-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0021_auto_20181117_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='device_is_active',
            new_name='branch_is_active',
        ),
    ]
