# Generated by Django 2.0.6 on 2018-11-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0022_auto_20181118_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='deliveryApi.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='deliveryApi.Organisation'),
            preserve_default=False,
        ),
    ]
