# Generated by Django 2.0.6 on 2018-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0025_auto_20181118_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.CharField(max_length=300),
        ),
    ]
