# Generated by Django 2.0.6 on 2018-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0026_auto_20181127_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_latitude',
            field=models.CharField(default='latitude', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_longitude',
            field=models.CharField(default='longitude', max_length=60),
            preserve_default=False,
        ),
    ]
