# Generated by Django 2.0.6 on 2018-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0027_auto_20181127_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_not_uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionlog',
            name='is_not_uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionlog',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='is_not_uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
