# Generated by Django 2.0.6 on 2018-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0028_auto_20181127_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_api_server_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_latitude',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_longitude',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_directory',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_photo_upload_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
