# Generated by Django 2.0.6 on 2018-11-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0029_auto_20181128_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsection',
            name='section_id',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='questionsection',
            name='section_name',
            field=models.CharField(default='Before Departure', max_length=40),
        ),
    ]
