# Generated by Django 2.0.6 on 2018-11-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0030_auto_20181129_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsection',
            name='question_section',
        ),
    ]
