# Generated by Django 2.0.6 on 2018-11-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0031_remove_questionsection_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='days_to_delete_photos',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=7, max_length=1),
        ),
    ]
