# Generated by Django 2.0.6 on 2018-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0035_remove_photo_is_not_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='drop_id',
            field=models.CharField(default='FAKE_DEROP', max_length=40),
        ),
        migrations.AddField(
            model_name='photo',
            name='run_id',
            field=models.CharField(default='FAKE_RUN', max_length=40),
        ),
    ]
