# Generated by Django 2.0.6 on 2018-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0036_auto_20181205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='drop_id',
            field=models.CharField(default='FAKE_DROP', max_length=40),
        ),
    ]
