# Generated by Django 2.0.6 on 2018-12-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0037_auto_20181205_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='files',
            new_name='file',
        ),
    ]
