# Generated by Django 2.0.6 on 2018-12-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0038_auto_20181205_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='days_to_delete_photos',
        ),
    ]
