# Generated by Django 2.0.6 on 2018-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0039_remove_organisation_days_to_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='days_to_delete_photos',
            field=models.IntegerField(default=7),
        ),
    ]
