# Generated by Django 2.0.6 on 2018-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0040_organisation_days_to_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
