# Generated by Django 2.0.6 on 2018-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0041_device_device_is_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
