# Generated by Django 2.0.6 on 2018-12-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0042_photo_is_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequests',
            options={'verbose_name_plural': 'password Reset Requests'},
        ),
        migrations.AlterField(
            model_name='questionsection',
            name='section_name',
            field=models.CharField(default='before departure', max_length=40),
        ),
    ]
