# Generated by Django 2.0.6 on 2018-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0043_auto_20181208_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
