# Generated by Django 2.0.6 on 2018-12-12 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0047_auto_20181212_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 16, 35, 13, 450712)),
        ),
    ]
