# Generated by Django 2.0.6 on 2018-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0048_auto_20181212_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
