# Generated by Django 2.0.6 on 2018-12-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0050_auto_20181212_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='q_id',
            field=models.IntegerField(default=219),
        ),
    ]
