# Generated by Django 2.0.6 on 2018-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0051_questionresponse_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='q_id',
            field=models.IntegerField(default=1),
        ),
    ]
