# Generated by Django 2.0.6 on 2020-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0054_auto_20181222_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_branch_user',
            field=models.BooleanField(default=False),
        ),
    ]
