# Generated by Django 2.0.6 on 2020-01-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0055_user_is_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryApi.Branch'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='driver_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
