# Generated by Django 5.0.6 on 2024-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApi', '0057_branchusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchusers',
            options={},
        ),
        migrations.AlterField(
            model_name='customercode',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customercode',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='drop_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_checked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_uploaded',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='run_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
